feat: add synthetics to ecs stacks module
chanzuckerberg/happy pull request #1008
Opened 2023-01-24 23:41 UTC by jakeyheath

2023-01-25 15:39 UTC, hspitzley-czi approved these changes

2023-01-25 15:40 UTC, hspitzley-czi requested changes
Looks like this check is failing https://github.com/chanzuckerberg/happy/actions/runs/4001518575/jobs/6867842984

2023-01-25 17:41 UTC, dtsai-czi approved these changes

2023-01-26 13:53 UTC, hspitzley-czi approved these changes

2023-01-26 13:53 UTC, merged